/// <reference path="../../typings/index.d.ts"/>
/// <reference path="../config/config.ts" />
/// <reference path="../objects/asset.ts" />
/// <reference path="../objects/label.ts" />
/// <reference path="../objects/button.ts" />
/// <reference path="../objects/scene.ts" />
/// <reference path="../scenes/menu.ts" />
/// <reference path="../scenes/game.ts" />
/// <reference path="../scenes/COME.ts" />
/// <reference path="../scenes/STAY.ts" />
/// <reference path="../scenes/SHOVEL.ts" />
/// <reference path="../scenes/PICKAXE.ts" />
/// <reference path="../scenes/TORCH.ts" />
/// <reference path="../scenes/LIGHT.ts" />
/// <reference path="../scenes/LEFTA.ts" />
/// <reference path="../scenes/RIGHTA.ts" />
/// <reference path="../scenes/LEFTB.ts" />
/// <reference path="../scenes/RIGHTB.ts" />
/// <reference path="../scenes/LEFTC.ts" />
/// <reference path="../scenes/RIGHTC.ts" />
/// <reference path="../scenes/LEFTD.ts" />
/// <reference path="../scenes/RIGHTD.ts" /> 
//# sourceMappingURL=_reference.js.map